"""Label-efficiency sweep for the extension study (trained with ../../train_vfm.py).

Two frozen arms compared as labelled data shrinks — the workshop's "learning from
limited data" question:

    le2-vitsp   frozen DINOv2 ViT-S/14, CLS+patch readout   (our VFM)
    le2-mnet    frozen MobileNetV2                          (CNN baseline encoder)

Both use the identical strong-but-frozen recipe (AdamW head, cosine+warmup,
flip aug, whole-split RAM cache), so the ONLY difference is the encoder. For each
training-set size the same random group subsets are shared by both arms (paired
comparison), and subsets are BN-safe (no size-1 final batch). Frozen, so every
run fits the ~2 GB of shared GPU we have — no fine-tuning / no full GPU needed.

    python generate_le_extension.py           # writes cnn/configs/le_ext/*.cfg
    bash ../../retarget_data_path.sh /path/annotations.json
    # then, e.g.:
    bash ../../run_extension.sh $(ls cnn/configs/le_ext/*.cfg)
"""
import itertools
import os
import random

DATA = "/workspace/autofish_dataset/annotations.json"  # retargeted later
VAL = "[1, 6, 11, 17, 25]"
TEST = "[10, 14, 20, 21, 22]"
TRAIN_FULL = [2, 3, 4, 5, 7, 8, 9, 12, 13, 15, 16, 18, 19, 23, 24]
GROUP_COUNTS = {1: 640, 2: 760, 3: 600, 4: 880, 5: 880, 6: 640, 7: 560, 8: 800,
                9: 960, 10: 920, 11: 640, 12: 640, 13: 880, 14: 840, 15: 800,
                16: 720, 17: 799, 18: 600, 19: 560, 20: 640, 21: 679, 22: 680,
                23: 560, 24: 560, 25: 920}
SIZES = [1, 2, 4, 8, 15]
K_SUBSETS = 3
BATCH = 32
SUBSET_SEED = 42

ARMS = [  # tag, MODEL_BACKEND
    ("vitsp", "dinov2_vits14-clspatch"),
    ("mnet", "mobilenet_v2"),
]

TEMPLATE = """\
# Auto-generated by generate_le_extension.py — train with ../../train_vfm.py.
# Label-efficiency: arm={tag}, {n} of 15 training groups, subset s{sid} (frozen).
[Config]
OUTPUT_DIR: ./output/le2-{tag}-{n:02d}grp-s{sid}/
MASKS_GT: {data}
TRAIN_GROUPS: {groups}
VAL_GROUPS: {val}
TEST_GROUPS: {test}

[Training]
CACHE_IMAGES: True
CACHE_SIZE_GIB: 8
NUM_EPOCHS: 150
BATCH_SIZE: {batch}
RANDOM_SEED: 42
LOSS: l1
OPTIMIZER: adamw
HEAD_LR: 1e-3
BACKBONE_LR: 0
WEIGHT_DECAY: 0.05
WARMUP_EPOCHS: 5
SCHEDULER: cosine
FLIP_AUG: True
GRAD_CLIP: 1.0

[Preprocessing]
CROP_TO_BBOX: True
MASKING_TYPE: rgb

[Model]
MODEL_BACKEND: {backend}
FREEZE_BACKEND: True
MODEL_SIZE: small
MODEL_INPUT_PLANE: False
MODEL_INPUT_BBOX: True
NORMALIZE_BBOX: True

[Augmentation]
AUGMENT_COLOR_TRAIN_IMAGES: True
AUGMENT_CROP_TRAIN_IMAGES: False
"""


def bn_safe(groups):
    return sum(GROUP_COUNTS[g] for g in groups) % BATCH != 1


def pick_subsets(n, k, rng):
    if n >= len(TRAIN_FULL):
        return [sorted(TRAIN_FULL)]
    seen, out, tries = set(), [], 0
    while len(out) < k and tries < 10000:
        tries += 1
        cand = tuple(sorted(rng.sample(TRAIN_FULL, n)))
        if cand in seen or not bn_safe(cand):
            continue
        seen.add(cand); out.append(list(cand))
    return out


def main():
    rng = random.Random(SUBSET_SEED)
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "le_ext")
    os.makedirs(out_dir, exist_ok=True)
    subsets = {n: pick_subsets(n, K_SUBSETS, rng) for n in SIZES}
    n_written = 0
    for (tag, backend), n in itertools.product(ARMS, SIZES):
        for sid, groups in enumerate(subsets[n]):
            cfg = TEMPLATE.format(tag=tag, n=n, sid=sid, backend=backend,
                                  batch=BATCH, groups=groups, data=DATA,
                                  val=VAL, test=TEST)
            with open(os.path.join(out_dir, f"le2-{tag}-{n:02d}grp-s{sid}.cfg"),
                      "w") as f:
                f.write(cfg)
            n_written += 1
    print(f"wrote {n_written} configs to {out_dir}")
    for n in SIZES:
        print(f"  size {n:2d}: {len(subsets[n])} subset(s) x {len(ARMS)} arms")


if __name__ == "__main__":
    main()
