"""Generate label-efficiency configs for the baseline and the VFM variant.

Task-description item: "studying how performance changes when the amount of
labeled training data is reduced." This is done WITHOUT touching the training
code: train.py already reads TRAIN_GROUPS from the config, so we emit one config
per (arm, #training-groups, subset draw).

Two design points the naive version got wrong, fixed here:

1. Variance must come from the DATA, not the torch seed. train.py only calls
   torch.manual_seed(RANDOM_SEED), which changes head init / shuffle / aug order
   but NOT which groups are used (TRAIN_GROUPS is read verbatim). The paper's
   low-data error bars come from averaging several RANDOM group subsets per
   size. So for each size < 15 we emit K different randomly-sampled subsets;
   all arms share the SAME subsets, so the comparison is paired.

2. Three arms, to answer the question fairly:
     - baseline_ft     : MobileNetV2, fine-tuned  (the baseline as published)
     - baseline_frozen : MobileNetV2, frozen       (control, same regime as VFM)
     - vfm             : DINOv2 ViT-S/14, frozen    (the VFM variant)
   The clean "does the ENCODER help under limited labels" comparison is
   baseline_frozen vs vfm (regime held fixed); baseline_ft is the paper-regime
   reference. All arms are runnable with no code edit.

A size-1 final training batch would crash the head's BatchNorm1d (train.py uses
drop_last=False). We know each group's instance count, so subsets whose total
count % BATCH_SIZE == 1 are rejected at generation time.

Run (writes into label_efficiency/ next to this file):
    python generate_label_efficiency.py
"""
import itertools
import os
import random

# Paper's 15 training groups and their instance counts (from annotations.json).
TRAIN_GROUPS_FULL = [2, 3, 4, 5, 7, 8, 9, 12, 13, 15, 16, 18, 19, 23, 24]
GROUP_COUNTS = {2: 760, 3: 600, 4: 880, 5: 880, 7: 560, 8: 800, 9: 960,
                12: 640, 13: 880, 15: 800, 16: 720, 18: 600, 19: 560,
                23: 560, 24: 560}
VAL_GROUPS = [1, 6, 11, 17, 25]
TEST_GROUPS = [10, 14, 20, 21, 22]

SIZES = [1, 2, 4, 8, 15]   # number of training groups (15 = full set)
K_SUBSETS = 3              # random subsets per size (size 15 has only one)
BATCH_SIZE = 32
SUBSET_SEED = 42           # reproducible subset draws

# (tag, MODEL_BACKEND, FREEZE_BACKEND)
ARMS = [
    ("baseline_ft", "mobilenet_v2", False),
    ("baseline_frozen", "mobilenet_v2", True),
    ("vfm", "dinov2_vits14", True),
]

TEMPLATE = """# Auto-generated by generate_label_efficiency.py -- do not edit by hand.
# Label-efficiency point: arm={tag}, {n} of 15 training groups, subset s{sid}.
[Config]
OUTPUT_DIR: ./output/le-{tag}-{n:02d}grp-s{sid}/
MASKS_GT: /workspace/autofish_dataset/annotations.json
TRAIN_GROUPS: {train_groups}
VAL_GROUPS: {val_groups}
TEST_GROUPS: {test_groups}

[Training]
CACHE_IMAGES: True
NUM_EPOCHS: 200
BATCH_SIZE: {batch}
RANDOM_SEED: 42
LOSS: l1

[Preprocessing]
CROP_TO_BBOX: True
MASKING_TYPE: rgb

[Model]
MODEL_BACKEND: {backend}
FREEZE_BACKEND: {freeze}
MODEL_SIZE: small
MODEL_INPUT_PLANE: False
MODEL_INPUT_BBOX: True
NORMALIZE_BBOX: True

[Augmentation]
AUGMENT_COLOR_TRAIN_IMAGES: True
AUGMENT_CROP_TRAIN_IMAGES: False
"""


def bn_safe(groups):
    """Reject subsets whose instance count leaves a size-1 final batch."""
    return sum(GROUP_COUNTS[g] for g in groups) % BATCH_SIZE != 1


def pick_subsets(n, k, rng):
    """k distinct, BN-safe, sorted subsets of n training groups."""
    if n >= len(TRAIN_GROUPS_FULL):
        return [sorted(TRAIN_GROUPS_FULL)]
    seen, out, attempts = set(), [], 0
    while len(out) < k and attempts < 10000:
        attempts += 1
        cand = tuple(sorted(rng.sample(TRAIN_GROUPS_FULL, n)))
        if cand in seen or not bn_safe(cand):
            continue
        seen.add(cand)
        out.append(list(cand))
    return out


def main():
    rng = random.Random(SUBSET_SEED)
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "label_efficiency")
    os.makedirs(out_dir, exist_ok=True)

    # Draw subsets once per size, shared by every arm (paired comparison).
    subsets_by_size = {n: pick_subsets(n, K_SUBSETS, rng) for n in SIZES}

    written = []
    for (tag, backend, freeze), n in itertools.product(ARMS, SIZES):
        for sid, groups in enumerate(subsets_by_size[n]):
            cfg = TEMPLATE.format(
                tag=tag, n=n, sid=sid, backend=backend, freeze=freeze,
                batch=BATCH_SIZE, train_groups=groups,
                val_groups=VAL_GROUPS, test_groups=TEST_GROUPS)
            path = os.path.join(out_dir, f"le-{tag}-{n:02d}grp-s{sid}.cfg")
            with open(path, "w") as f:
                f.write(cfg)
            written.append(path)

    print(f"wrote {len(written)} configs to {out_dir}")
    for n in SIZES:
        subs = subsets_by_size[n]
        print(f"  size {n:2d}: {len(subs)} subset(s) x {len(ARMS)} arms -> "
              f"{[s for s in subs]}")


if __name__ == "__main__":
    main()
